### ISSUE TITLE
Migrate from Hugo to Next.js

### ISSUE THREAD

**Issue by mii288** [oystersjp/oystersjp.github.io#78]
## Contribution

1. [こちらのKANBAN](https://github.com/oystersjp/oystersjp.github.io/projects/1)のTodoから好きなものを選んでください
2. 選んだissueのAssigneesをあなたに変更し、ステータスをTodoからIn progressへ変更してください。
3. [master-nextjs](https://github.com/oystersjp/oystersjp.github.io/tree/master-nextjs) からブランチを切って作業を行い、作業が完了したあとは基本的に同ブランチないし適切なブランチへPRを作ってください。(例: #90)
※選んだissueの番号をPR内容あるいはコミットメッセージに含めるようにしてください

### SVGを読み込むサンプルコード

https://github.com/oystersjp/oystersjp.github.io/blob/42857413a5081de6d09b65d2df85d8432d925122/components/Logo/Logo.tsx#L1-L7

### 画像のリサイズ方法

[README.md>画像の最適化方法](https://github.com/oystersjp/oystersjp.github.io/blob/master-nextjs/README.md#%E7%94%BB%E5%83%8F%E3%81%AE%E6%9C%80%E9%81%A9%E5%8C%96%E6%96%B9%E6%B3%95%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6) を確認してください

----
- Project: https://github.com/oystersjp/oystersjp.github.io/projects/1
- Milestone: https://github.com/oystersjp/oystersjp.github.io/milestone/1

**Comment by mii288** [comment]
# オンライン合宿リモート（ゆるゆる）

## 目的

- Hugo製のLPをNext(React)へリプレイス

### やらないこと

- CSSのリファクタはなし（そのまま移します）
- カルーセル、アニメーションの JS→ 移行しません
- デプロイ先の変更

## TODO

進捗は[Github Project](https://github.com/oystersjp/oystersjp.github.io/projects/1)で管理するのでTODOは更新されなくなりました。
<details><summary>簡易的な見積もりや作業内容を確認したい場合はこちらをクリック</summary>

### 1. 環境構築
- [x] ESLint 入れる
- CI
  - [x] 自動デプロイ...**2h**
  - [x] (want) Lint
  - [ ] (want) CircleCI設定ファイルの削除

### 2. 移行作業
- [x] Global CSS(themes/custom.css)の読み込み
    - icon読み込み
- [ ] 各HTMLリプレイス※基本HTMLにテキストをベタ書きする
  - [x] layout/index.html...**1h**
    - テーマファイル用のCSSの読み込み
    - 画像の読み込み
  - [x] partials/head.html...**0.2h**
    - <head/>の設定
  - [x] partials/navigation.html...**0.2h**
    - 画像の読み込み
    - マークアップごと移動
  - [ ] partials/hero-area.html...**0.2h**
    - 画像の読み込み
    - マークアップごと移動
  - [ ] 見出しコンポーネントを作る...**0.5h**
  - [ ] コンテンツを移設...**3.0h**
    - [x] partials/team.html
      - 画像の読み込み
      - マークアップごと移動
      - ディレクトリ管理(ローカルのファイルを読みこんで、動的にコンポーネントを生成する)
        - ディレクトリの構成イメージ(できればTSでメンバーデータを管理したいが、処理が面倒であればjsonにする）
          ```
          team/
            ├ team.tsx
            └ members/
              ├ {name}/
              |   ├ index.ts
              |   └ picture.jpg
              └ taro/
                  ├ index.ts
                  └ picture.jpg
          ```
    - [ ] [分担] partials/about.html...**0.3h**
      - 画像の読み込み
      - マークアップごと移動
    - [ ] [分担] partials/contact.html...**0.3h**
      - 画像の読み込み
      - マークアップごと移動
    - [ ] [分担] partials/products.html...**0.3h**
      - 画像の読み込み
      - マークアップごと移動
    - [ ] [分担] partials/activities.html...**0.3h**
      - 画像の読み込み
      - マークアップごと移動
    - [ ] [分担] partials/memories.html...**0.3h**
      - 画像の読み込み
      - マークアップごと移動
    - [ ] [分担] partials/footer.html...**0.3h**
      - 画像の読み込み
      - マークアップごと移動
  - [ ] ~~partials/preloader.html~~
    - 移行しない

</details>
